os: windows
language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run make
deploy:
  provider: script
  script:
    - npm install
    - npm run publish
  on:
    tags: true
    branch: travis-test
