os: windows
language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run make
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run publish
  on:
    branch: release
