dist: xenial
language: node_js
node_js:
  - lts/*
before_install:
  - sudo dpkg --add-architecture i386
  - wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https ca-certificates -y
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update -y
install:
  - sudo apt-get install -y --install-recommends winehq-stable
  - sudo apt install mono-devel -y
  - npm install
script:
  - npm run make
  - npx electron-forge make --platform=win32
