name: Node.js CI

on:
  pull_request:
    branches: [ master, release ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run make
      - run: npm run publish
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
